baseurl: "/"
languageCode: "en-us"
languageLang: "en"
title: "Maksim Gorodov"

# https://gohugo.io/getting-started/configuration/#configure-blackfriday
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds: ["RSS", "taxonomy", "taxonomyTerm"]
